version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: innerhealth_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: innerhealth
      MYSQL_USER: innerhealth
      MYSQL_PASSWORD: innerpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: innerhealth_api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"

      # ===== JWT VARIÁVEIS =====
      Jwt__Key: "sua-chave-ultra-secreta"
      Jwt__Issuer: "InnerHealthAPI"
      Jwt__Audience: "InnerHealthClient"

      # ===== DATABASE VARIÁVEIS =====
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=innerhealth;user=root;password=root123;"

volumes:
  mysql_data:
